### ISSUE TITLE
Can't receive two-factor authentication code

### ISSUE THREAD

**Issue by LionYu66** [altstoreio/AltStore#1120]
Can't receive two-factor verification code on ios 16.3, but can receive the code when I login icloud.com, Since I have advanced data protection turned on, I'm guessing that this new feature is a conflict with altstore.

**Comment by RAtIG** [comment]
Hello, I can confirm I have the same issue. On Windows, can't get a verification code to install altstore. 

Tried [this method](https://github.com/rileytestut/AltStore/issues/61#issuecomment-989174246), not working.

Thank you

![image](https://user-images.githubusercontent.com/47703127/215622729-0967bd0c-ccc4-41b2-9f98-d338684358f2.png)

**Comment by sintclau** [comment]
Hi, I have the same issue on Windows. Tried all the methods mentioned here and it didn't work.
I have advanced data protection tuned on too.

**Comment by shanegillio** [comment]
Hi there! Have you installed the latest version? We have fixed up some issues with 2FA codes not being shows for windows users.

**Comment by LionYu66** [comment]
Hi,I think it work well now, but the link you gave in altstore of iCloud for Windows still can’t recive the 2FA codes when advanced data protection was on, I still need to login with an account which without advanced  data protection was on.
